version: '3'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dckerfile
    hostname: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: password

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake

    volumes:
    - "db-data:/var/lib/mysql"
    - "./docker/mysql/my.conf:/etc/mysql/my.conf"
    - "./docker/mysql/init/:/docker-entrypoint-initdb.d"
    links:
    - mysql
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: sample_docker_compose
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/sample_docker_compose
    command: go run main.go

    volumes:
      db-data:
        driver: local